[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[functions]
  node_bundler = "esbuild"
"scripts": {
  "build": "echo 'No build step required'"
}
